server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456

logging:
  level:
    cn.grandtime.demo: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    database-id: mysql
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'